### ISSUE TITLE
Synchronize JSON schema and form validation requirements

### ISSUE THREAD

**Issue by deweller** [engineer-dao/platform#111]
Some fields are optional in the form, but required in the JSON schema.  Make sure these are in sync.

**Comment by reisr3** [comment]
Removing the secondary validation for forms effectively solves this.

**Comment by deweller** [comment]
I think the JSON schema should be the ultimate source of truth for the meta data validation.

The form validation is just a UI helper to make it easier on the user.

**Comment by reisr3** [comment]
Well they're effectively doing the same thing though. Formik is just using a form validation library called `yup` and the other validation was using `ajv`. They're both easily bypass-able in the frontend though. Maybe we are saying the same thing?

**Comment by reisr3** [comment]
I agree 100% that we should do some validation reading from IPFS. In fact, we might want to do that in a backend service... it's an extra hop but we can better control the critical data that comes into the platform.
