### ISSUE TITLE
useWalletProvider.ts onChainChanged resets Wallet Action

### ISSUE THREAD

**Issue by karmabadger** [engineer-dao/platform#132]
useWalletProvider.ts onChainChanged resets Wallet Action, is that the behavior that we want? if I undersatnd correctly this pretty much disconnects the wallet right? Perhaps if it instead brings out the popup that says "wrong network" would be a better action?

```ts
const onChainChanged = () => {
    setWalletConnection(resetWalletAction);
  };

  const onConnected = (info: { chainId: number }) => {};

  const bindConnectionEvents = (connection: EventEmitter) => {
    connection.on('accountsChanged', onAccountsChanged);
    connection.on('chainChanged', onChainChanged);
    connection.on('connect', onConnected);
  };
```

**Comment by reisr3** [comment]
@karmabadger Thanks for completing this!
