### ISSUE TITLE
Send a message to Discord on `Job Reported`

### ISSUE THREAD

**Issue by reisr3** [engineer-dao/platform#133]
Spawned from https://github.com/engineer-dao/platform/issues/77

https://discord.com/developers/docs/resources/channel#create-message

- Create a new backend service that posts a message to a private Discord channel
- Message should include `Job Reported`, link to job, timestamp, and other relevant info.
- Should happen in the backend

**Comment by deweller** [comment]
Also do this for `JobDisputed`.

**Comment by deweller** [comment]
Inspiration here:
https://gist.github.com/ianklatzco/769d9e3a991dc2f443a2e105b0157117

Build a small library to allow for expansion to some other basic notifications as well (JobPosted, JobCompleted, etc)

**Comment by reisr3** [comment]
I'm going to make a new Issue for other reports to Discord. This one was easier because there is already a backend route for `add-report` to IPFS, but we need a more general route for posting to Discord (one that is protected as well.)

**Comment by reisr3** [comment]
https://github.com/engineer-dao/platform/issues/154
