### ISSUE TITLE
Connect Create Contract to `postJob` [Happy Path]

### ISSUE THREAD

**Issue by reisr3** [engineer-dao/platform#15]
- Connect the "Create Contract" form to the `postJob` method of the main contract
- Should successfully create a job when the required fields are there
- Upon successful job creation, the user should be redirected to the "Single Job" contract view

## Notifications
- Upon creating a new contract, a "Contract successfully created" toast notification should pop up at the bottom of the screen. Dependent on notifications service creation.

**Comment by deweller** [comment]
Didn't do a toast notification, but the user will be redirected to the job details page by ID.
