### ISSUE TITLE
Cache IPFS metadata in the backend

### ISSUE THREAD

**Issue by reisr3** [engineer-dao/platform#155]
Currently, we're loading IPFS once directly from IPFS and then caching in frontend local storage.

This is super error prone, and adds complexity to the frontend. However, IPFS is slow and we need a way to quickly load metadata.

Use Firebase, Redis, or a similar web3 tech to store IPFS data!

**Comment by deweller** [comment]
While doing this, change localstorage cache to use the CID and not the Job ID.
