### ISSUE TITLE
Create Contract validation

### ISSUE THREAD

**Issue by reisr3** [engineer-dao/platform#16]
- Use Formik to create validation rules for each field in Create Contract
- Reference the `postJob` method in the main contract. Contract should not be able to be created without each field being available and populated with reasonable information. This will require some research and thinking about each field (for example, there is a minimum bounty we need to enforce.)
- If a field is invalid, show the validation error message below the field in red. [See TailwindUI for examples.](https://tailwindui.com/components/application-ui/forms/input-groups#component-7a5297f99a5ed22df80939dd1986de5f)
- Disable the `Fund & Create` button until the form is valid

**Comment by deweller** [comment]
In addition, complete some of the incomplete items in #37

- Switch to `useFormikContext` for fields
- Update PaymentSummary component to do bounty calculations based on the buy-in percentage
- remove `CreateFormValues` type or convert it into an interface (in interfaces folder) if it is still necessary
- remove formData, setValidatedFormData state and use Formik
- Implement the validate prop
