### ISSUE TITLE
Store the JobMetaData object on IPFS and put only the ipfs hash on chain

### ISSUE THREAD

**Issue by indeavr** [engineer-dao/platform#35]
Storing big stringified objects on chain isn't optimal and leads to unnecessary gas costs. 

IMO we should upload & pin the metadata on IPFS first before submitting only the hash to `postJob()`. 
moralis / nftport / nft.storage - all have convenient helpers.  

[Moralis Docs](https://docs.moralis.io/moralis-server/files/ipfs#saving-objects) 

The `postJob` contract function should be constrained to only accept ipfs hashes.

**Comment by indeavr** [comment]
IPFS urls can be used for the dispute resolvement as well -> as the `reason`

**Comment by deweller** [comment]
Infura also has an IPFS API
