### ISSUE TITLE
Research which network to use

### ISSUE THREAD

**Issue by reisr3** [engineer-dao/platform#42]
- Polygon?
- L2?
- xDAI?

**Comment by indeavr** [comment]
What are some key metrics that will help us choose ? 
* tx cost
* exposure & partners 

Polygon, Avax, Optimism seem like the top 3 leading options for us right now.

**Comment by deweller** [comment]
Here's a helpful site: https://l2beat.com/ and https://l2fees.info/


**The case for Polygon**

Fees are significantly cheaper than even Arbitrum.
Polygon (PoS) has $5.39b TVL.
Polygon just raised $350M to continue development.

**The case against Polygon**

Polygon PoS is a sidechain and relies on PoS validators for security - it does not inherit the full security of Ethereum L1.
Fees are so cheap, users have seen problems with the chain being flooded and transactions not going through.


**xDAI**
xDAI has 219.33m TVL and is also a PoS sidechain.

**Other options**

Arbitrum One is a true ZK-Rollup secured by Ethereum with 2.09b TVL.
Polygon Hermez is a true ZK-Rollup secured by Ethereum.  But it does not have adoption yet (178K TVL).

**Comment by deweller** [comment]
If I had to pick a starting chain right now, I would choose Polygon.

I think it offers the right level of security and best chance of long term sustainability with an acceptable fee structure for our application.  Polygon has pretty good ecosystem support and is growing.

I think Ethereum has the best chance to win the long-term game of smart contract execution platforms, so I think it wise to choose an Ethereum L2 solution.

**Comment by reisr3** [comment]
IMHO - @deweller satisfactorily completed this "spike" task. Polygon seems like our best bet. We can always add more supported chains after launch.
