### ISSUE TITLE
Add check for existing token to updatePaymentTokens

### ISSUE THREAD

**Issue by deweller** [engineer-dao/platform#52]
`updatePaymentTokens` should guard against a token that already xists in `tokensList`.

If a token is added twice and then removed, the token will remain in `tokensList` when it shouldn't.

**Comment by indeavr** [comment]
Fixed in [PR 38](https://github.com/engineer-dao/platform/pull/38/commits/2963c404761a41d6aab6ffd7b1cee8eee440fdf7)
