### ISSUE TITLE
Decide about flagging reported jobs

### ISSUE THREAD

**Issue by deweller** [engineer-dao/platform#77]
When a job is reported, should we flag it or put it in a reported state?

A reported state means:
- The job cannot progress (can't be completed or accepted)
- This means the supplier and engineer may lose a day (or two) in their timeframe

A flag means:
- The job progresses normally and nothing happens until the report is resolved
- Only a flag is shown in the UI

**Comment by deweller** [comment]
Question was raised in https://github.com/engineer-dao/platform/pull/72

**Comment by reisr3** [comment]
For MVP, this just needs to alert us somehow. Maybe that is just through a private channel in Discord? That would be a pretty nice way to do it.

After MVP, I do think there should be an "Admin Dashboard" area as well where we can easily attend to Reported jobs.

**Comment by reisr3** [comment]
https://discord.com/developers/docs/resources/channel#create-message

Posting a message to a private channel in our Discord could work for now. This would need to get wrapped in a new cloud function.

**Comment by reisr3** [comment]
@deweller Let me know if you disagree - otherwise I'm going to close this in favor of the action item created above.

**Comment by deweller** [comment]
Agree about the Discord message.

But we still need to decide on the data structure for removing or flagging the job in the smart contract.

**Comment by deweller** [comment]
I recommend moving the job into a Reported state instead of just flagging it.  This is consistent with the finite state method of handling job statuses.  I think this is less prone to error and is easier to deal with on the front end.  It prevents any activity on a reported job.

The downside is that a false positive report can cause a delay for the engineer to complete or get paid.

**Comment by reisr3** [comment]
Hmm... the only thing I worry about is that we're going to get spammed. It would be very easy to report contracts, put them in `Reported` status (unable to function), and then we have to go back and sort everything out.

I kinda think that reporting should be "soft". Like it alerts us - but doesn't actually do anything with the contract. Otherwise, people could abuse this.

**Comment by deweller** [comment]
The most recent approach we discussed is that reporting a job costs a deposit.  And if it is a false positive, the reporter loses their deposit.  

That should prevent report spamming.
