### ISSUE TITLE
Prompt the user to switch to the correct network

### ISSUE THREAD

**Issue by deweller** [engineer-dao/platform#83]
When loading the site and Metamask is connected to the wrong network (Ethereum instead of Polygon for example), prompt the user to switch to the correct network.

**Comment by indeavr** [comment]
Not sure how it's implemented right now, but make sure that we're calling window.ethereum only when a button is pressed (not on load) ! 
Users hate this intrusive behavior.

**Comment by deweller** [comment]
Agreed.  This would be when you connect a wallet after clicking the connect button, but you connect to the wrong network.

**Comment by indeavr** [comment]
I've also seen many dapps that prompt the user with a a `ready to add chain config` (in the case when you don;t have the Poly network in your metamask). This could be post MVP ofcourse.
